import { memo } from "react";
import {
  X,
  Dot,
  User,
  Copy,
  Mail,
  Save,
  Globe,
  Phone,
  Check,
  Search,
  Circle,
  Loader2,
  Sliders,
  FileIcon,
  ArrowLeft,
  BrainIcon,
  ChevronUp,
  FolderIcon,
  ArrowRight,
  SchoolIcon,
  FilterIcon,
  ChevronLeft,
  ChevronDown,
  GripVertical,
  ChevronRight,
  MoreHorizontal,
  FolderOpenIcon,
  BriefcaseBusiness,
  MessageCircleHeart,
} from "lucide-react";

export const MemoizedLucideReactIcons = {
  X: memo(X),
  Dot: memo(Dot),
  User: memo(User),
  Save: memo(Save),
  Mail: memo(Mail),
  Copy: memo(Copy),
  Globe: memo(Globe),
  Phone: memo(Phone),
  Check: memo(Check),
  Circle: memo(Circle),
  Search: memo(Search),
  Loader2: memo(Loader2),
  Sliders: memo(Sliders),
  FileIcon: memo(FileIcon),
  ChevronUp: memo(ChevronUp),
  ArrowLeft: memo(ArrowLeft),
  BrainIcon: memo(BrainIcon),
  FolderIcon: memo(FolderIcon),
  ArrowRight: memo(ArrowRight),
  SchoolIcon: memo(SchoolIcon),
  FilterIcon: memo(FilterIcon),
  ChevronLeft: memo(ChevronLeft),
  ChevronDown: memo(ChevronDown),
  GripVertical: memo(GripVertical),
  ChevronRight: memo(ChevronRight),
  MoreHorizontal: memo(MoreHorizontal),
  FolderOpenIcon: memo(FolderOpenIcon),
  BriefcaseBusiness: memo(BriefcaseBusiness),
  MessageCircleHeart: memo(MessageCircleHeart),
};
